// Hand-curated aliases, soft-enums, and composite types layered on top of the
// auto-generated `./types.ts`. Regenerate the base types with:
//   npx supabase gen types typescript --linked --schema public > src/lib/supabase/types.ts
// Anything in this file survives that regeneration.

import type { Tables, TablesInsert, TablesUpdate, Enums } from './types';

export type { Database, Tables, TablesInsert, TablesUpdate, Enums, Json } from './types';

// ── Postgres ENUM aliases ────────────────────────────────────────────────────

export type OrderStatus    = Enums<'order_status'>;
export type StaffRole      = Enums<'staff_role'>;
export type KDSStation     = Enums<'kds_station'>;
export type LoyaltyTier    = Enums<'loyalty_tier'>;
export type CouponType     = Enums<'coupon_type'>;
export type PaymentMethod  = Enums<'payment_method'>;
export type PaymentStatus  = Enums<'payment_status'>;

// ── Soft enums (Postgres `string` columns with check constraints) ────────────

export type KDSStatus            = 'pending' | 'preparing' | 'ready' | 'delivered';
export type EmploymentType       = 'full_time' | 'part_time' | 'contract' | 'temporary';
export type ShiftStatus          = 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
export type LeaveType            = 'annual' | 'sick' | 'emergency' | 'unpaid' | 'other';
export type LeaveStatus          = 'pending' | 'approved' | 'rejected' | 'cancelled';
export type PointsTransactionType = 'earned' | 'redeemed' | 'expired' | 'bonus';
export type ContactMessageStatus = 'new' | 'read' | 'replied';
export type AuditLogAction       = 'INSERT' | 'UPDATE' | 'DELETE';

// ── Row aliases ──────────────────────────────────────────────────────────────

export type BranchRow             = Tables<'branches'>;
export type CustomerRow           = Tables<'customers'>;
export type OrderRow              = Tables<'orders'>;
export type OrderItemRow          = Tables<'order_items'>;
export type MenuItemSyncRow       = Tables<'menu_items_sync'>;
export type StaffBasicRow         = Tables<'staff_basic'>;
export type ShiftRow              = Tables<'shifts'>;
export type TimeEntryRow          = Tables<'time_entries'>;
export type LeaveRequestRow       = Tables<'leave_requests'>;
export type AuditLogRow           = Tables<'audit_logs'>;
export type ContactMessageRow     = Tables<'contact_messages'>;
export type CustomerProfileRow    = Tables<'customer_profiles'>;
export type PointsTransactionRow  = Tables<'points_transactions'>;
export type CouponRow             = Tables<'coupons'>;
export type CouponRedemptionRow   = Tables<'coupon_redemptions'>;
export type CouponTemplateRow     = Tables<'coupon_templates'>;
export type CouponUsageRow        = Tables<'coupon_usages'>;
export type KDSQueueRow           = Tables<'kds_queue'>;
export type DriverLocationRow     = Tables<'driver_locations'>;
export type PaymentRow            = Tables<'payments'>;
export type PaymentWebhookRow     = Tables<'payment_webhooks'>;
export type ReportAuditLogRow     = Tables<'report_audit_log'>;

// `staff_basic` already includes the extended employment columns, so the legacy
// StaffExtendedRow alias points at the same row type.
export type StaffExtendedRow = StaffBasicRow;

// ── Insert / Update aliases ──────────────────────────────────────────────────

export type OrderInsert              = TablesInsert<'orders'>;
export type OrderItemInsert          = TablesInsert<'order_items'>;
export type ContactMessageInsert     = TablesInsert<'contact_messages'>;
export type CustomerProfileInsert    = TablesInsert<'customer_profiles'>;
export type PointsTransactionInsert  = TablesInsert<'points_transactions'>;
export type CouponInsert             = TablesInsert<'coupons'>;
export type CouponUpdate             = TablesUpdate<'coupons'>;
export type CouponUsageInsert        = TablesInsert<'coupon_usages'>;
export type PaymentInsert            = TablesInsert<'payments'>;
export type PaymentUpdate            = TablesUpdate<'payments'>;
export type DriverLocationInsert     = TablesInsert<'driver_locations'>;
export type DriverCashHandoverInsert = TablesInsert<'driver_cash_handovers'>;
export type DriverCashHandoverUpdate = TablesUpdate<'driver_cash_handovers'>;
export type DriverOrderIssueInsert   = TablesInsert<'driver_order_issues'>;
export type ShiftInsert              = TablesInsert<'shifts'>;
export type ShiftUpdate              = TablesUpdate<'shifts'>;
export type LeaveRequestInsert       = TablesInsert<'leave_requests'>;
export type LeaveRequestUpdate       = TablesUpdate<'leave_requests'>;
export type TimeEntryInsert          = TablesInsert<'time_entries'>;
export type ReportAuditLogInsert     = TablesInsert<'report_audit_log'>;

// ── Composite / joined types (not generated by supabase gen types) ───────────

export type OrderWithItems = OrderRow & {
  order_items: OrderItemRow[];
  branch: BranchRow | null;
};

export type ShiftWithStaff = ShiftRow & {
  staff_basic: Pick<StaffBasicRow, 'name' | 'role'>;
};

export type KDSQueueItem = KDSQueueRow & {
  order_items: Pick<OrderItemRow, 'name_ar' | 'name_en' | 'quantity' | 'selected_size' | 'selected_variant'>;
  orders: Pick<OrderRow, 'customer_name' | 'notes' | 'branch_id' | 'status' | 'created_at'>;
};

export type KDSOrder = Omit<OrderRow, 'status'> & {
  status: 'accepted' | 'preparing' | 'ready';
  order_items: Array<{
    id: string;
    name_ar: string;
    name_en: string;
    quantity: number;
    selected_size: string | null;
    selected_variant: string | null;
  }>;
};

export type DriverOrder = OrderRow & {
  order_items: Pick<OrderItemRow, 'name_ar' | 'name_en' | 'quantity' | 'selected_size' | 'selected_variant'>[];
  payments?: { method: PaymentMethod } | null;
  cash_settlement?: Array<{ handover_id: string }> | null;
  // Added by migration 037 — manually typed until types.ts is regenerated
  cash_settled_at?: string | null;
  cash_settlement_id?: string | null;
  // Added by migration 040
  tip_bhd?: number | null;
};

// Re-narrow `audit_logs.action` for safer call sites — the column is a generic
// `string` in Postgres but only ever holds one of three values in practice.
export type TypedAuditLogRow = Omit<AuditLogRow, 'action'> & { action: AuditLogAction };

// ── Inventory types (migration 035 — not yet in auto-gen types.ts) ──────────

export type IngredientUnit = 'g'|'kg'|'ml'|'l'|'unit'|'tbsp'|'tsp'|'oz'|'lb'|'piece'|'portion'|'bottle'|'can'|'bag'|'box'
export type AbcClass = 'A'|'B'|'C'
export type InventoryMovementType = 'reservation'|'consumption'|'release'|'purchase'|'count_adjust'|'waste'|'transfer_in'|'transfer_out'|'prep_production'|'prep_consumption'|'catering_reserve'|'catering_release'|'opening_balance'|'adjustment'
export type StorageTemp = 'frozen'|'chilled'|'ambient'|'dry'
export type PrepStorageTemp = 'frozen'|'chilled'|'ambient'
export type IngredientCategory = 'protein'|'grain'|'vegetable'|'dairy'|'seafood'|'spice'|'oil'|'beverage'|'sauce'|'packaging'|'cleaning'|'disposable'|'other'
export type PrepUnit = 'g'|'kg'|'ml'|'l'|'unit'|'portion'|'batch'
export type AllergenType = 'gluten'|'dairy'|'eggs'|'nuts'|'peanuts'|'soy'|'fish'|'shellfish'|'sesame'|'mustard'|'celery'|'lupin'|'molluscs'|'sulphites'
export type AlertSeverity = 'info'|'warning'|'critical'
export type ParDayType = 'default'|'weekend'|'ramadan'|'event'|'holiday'

export interface IngredientRow {
  id: string; name_ar: string; name_en: string; unit: IngredientUnit
  purchase_unit: string|null; purchase_unit_factor: number|null
  cost_per_unit: number; ideal_cost_pct: number|null; default_yield_factor: number
  category: IngredientCategory|null; abc_class: AbcClass; barcode: string|null
  reorder_point: number|null; max_stock_level: number|null; reorder_qty: number|null
  shelf_life_days: number|null; storage_temp: StorageTemp|null; supplier_id: string|null
  is_active: boolean; notes: string|null; created_at: string; updated_at: string
}

export interface SupplierRow {
  id: string; name_ar: string; name_en: string|null; phone: string|null
  email: string|null; is_active: boolean; created_at: string
}

export interface PrepItemRow {
  id: string; name_ar: string; name_en: string; unit: PrepUnit; batch_yield_qty: number
  shelf_life_hours: number|null; storage_temp: PrepStorageTemp|null
  is_active: boolean; notes: string|null; created_at: string
}

export interface PrepItemIngredientRow {
  id: string; prep_item_id: string; ingredient_id: string; quantity: number; yield_factor: number|null
}

export interface RecipeRow {
  id: string; menu_item_slug: string; ingredient_id: string|null; prep_item_id: string|null
  quantity: number; is_optional: boolean; variant_key: string|null; yield_factor: number|null
  notes: string|null; updated_by: string|null; updated_at: string
}

export interface InventoryStockRow {
  id: string; branch_id: string; ingredient_id: string; on_hand: number
  reserved: number; catering_reserved: number; reorder_point: number|null
  max_stock_level: number|null; last_movement_at: string|null
  last_count_at: string|null; created_at: string
}

export interface InventoryMovementRow {
  id: string; branch_id: string; ingredient_id: string|null; prep_item_id: string|null
  movement_type: InventoryMovementType; quantity: number; unit_cost: number|null
  order_id: string|null; performed_by: string|null; performed_at: string; notes: string|null
}

export interface InventoryAlertRow {
  id: string; branch_id: string|null; ingredient_id: string|null; alert_type: string
  severity: AlertSeverity; message: string; metadata: Record<string,unknown>
  is_read: boolean; created_at: string
}

export interface SupplierPriceHistoryRow {
  id: string; ingredient_id: string; supplier_id: string; unit_cost: number
  purchase_order_id: string|null; effective_at: string
}

export interface ParLevelRow {
  id: string; branch_id: string; ingredient_id: string; day_type: ParDayType
  par_qty: number; reorder_qty: number
}

export interface LowStockAlert {
  ingredient_id: string; name_ar: string; name_en: string; abc_class: AbcClass
  on_hand: number; available: number; par_qty: number|null; reorder_point: number|null
  days_to_out: number|null; nearest_expiry: string|null; suggested_order: number|null
}

export interface ExpiryReportRow {
  ingredient_id: string; name_ar: string; name_en: string; lot_id: string
  lot_number: string|null; quantity_remaining: number; expires_at: string
  days_remaining: number; stock_value_bhd: number
}

export interface DishCogsRow {
  slug: string; name_ar: string; name_en: string; selling_price: number|null
  cost_bhd: number; profit_bhd: number; margin_pct: number|null
}

export interface InventoryValuationRow {
  branch_id: string; branch_name: string; category: string|null
  ingredient_count: number; total_value_bhd: number; reserved_value_bhd: number
}
