// Hand-curated aliases, soft-enums, and composite types layered on top of the
// auto-generated `./types.ts`. Regenerate the base types with:
//   npx supabase gen types typescript --linked --schema public > src/lib/supabase/types.ts
// Anything in this file survives that regeneration.

import type { Tables, TablesInsert, TablesUpdate, Enums } from './types';

export type { Database, Tables, TablesInsert, TablesUpdate, Enums, Json } from './types';

// ── Postgres ENUM aliases ────────────────────────────────────────────────────

export type OrderStatus    = Enums<'order_status'>;
export type StaffRole      = Enums<'staff_role'>;
export type KDSStation     = Enums<'kds_station'>;
export type LoyaltyTier    = Enums<'loyalty_tier'>;
export type CouponType     = Enums<'coupon_type'>;
export type PaymentMethod  = Enums<'payment_method'>;
export type PaymentStatus  = Enums<'payment_status'>;

// ── Soft enums (Postgres `string` columns with check constraints) ────────────

export type KDSStatus            = 'pending' | 'preparing' | 'ready' | 'delivered';
export type EmploymentType       = 'full_time' | 'part_time' | 'contract' | 'temporary';
export type ShiftStatus          = 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
export type LeaveType            = 'annual' | 'sick' | 'emergency' | 'unpaid' | 'other';
export type LeaveStatus          = 'pending' | 'approved' | 'rejected' | 'cancelled';
export type PointsTransactionType = 'earned' | 'redeemed' | 'expired' | 'bonus';
export type ContactMessageStatus = 'new' | 'read' | 'replied';
export type AuditLogAction       = 'INSERT' | 'UPDATE' | 'DELETE';

// ── Row aliases ──────────────────────────────────────────────────────────────

export type BranchRow             = Tables<'branches'>;
export type CustomerRow           = Tables<'customers'>;
export type OrderRow              = Tables<'orders'>;
export type OrderItemRow          = Tables<'order_items'>;
export type MenuItemSyncRow       = Tables<'menu_items_sync'>;
export type StaffBasicRow         = Tables<'staff_basic'>;
export type ShiftRow              = Tables<'shifts'>;
export type TimeEntryRow          = Tables<'time_entries'>;
export type LeaveRequestRow       = Tables<'leave_requests'>;
export type AuditLogRow           = Tables<'audit_logs'>;
export type ContactMessageRow     = Tables<'contact_messages'>;
export type CustomerProfileRow    = Tables<'customer_profiles'>;
export type PointsTransactionRow  = Tables<'points_transactions'>;
export type CouponRow             = Tables<'coupons'>;
export type CouponRedemptionRow   = Tables<'coupon_redemptions'>;
export type CouponTemplateRow     = Tables<'coupon_templates'>;
export type CouponUsageRow        = Tables<'coupon_usages'>;
export type KDSQueueRow           = Tables<'kds_queue'>;
export type DriverLocationRow     = Tables<'driver_locations'>;
export type PaymentRow            = Tables<'payments'>;
export type PaymentWebhookRow     = Tables<'payment_webhooks'>;
export type ReportAuditLogRow     = Tables<'report_audit_log'>;

// `staff_basic` already includes the extended employment columns, so the legacy
// StaffExtendedRow alias points at the same row type.
export type StaffExtendedRow = StaffBasicRow;

// ── Insert / Update aliases ──────────────────────────────────────────────────

export type OrderInsert              = TablesInsert<'orders'>;
export type OrderItemInsert          = TablesInsert<'order_items'>;
export type ContactMessageInsert     = TablesInsert<'contact_messages'>;
export type CustomerProfileInsert    = TablesInsert<'customer_profiles'>;
export type PointsTransactionInsert  = TablesInsert<'points_transactions'>;
export type CouponInsert             = TablesInsert<'coupons'>;
export type CouponUpdate             = TablesUpdate<'coupons'>;
export type CouponUsageInsert        = TablesInsert<'coupon_usages'>;
export type PaymentInsert            = TablesInsert<'payments'>;
export type PaymentUpdate            = TablesUpdate<'payments'>;
export type DriverLocationInsert     = TablesInsert<'driver_locations'>;
export type DriverCashHandoverInsert = TablesInsert<'driver_cash_handovers'>;
export type DriverCashHandoverUpdate = TablesUpdate<'driver_cash_handovers'>;
export type DriverOrderIssueInsert   = TablesInsert<'driver_order_issues'>;
export type ShiftInsert              = TablesInsert<'shifts'>;
export type ShiftUpdate              = TablesUpdate<'shifts'>;
export type LeaveRequestInsert       = TablesInsert<'leave_requests'>;
export type LeaveRequestUpdate       = TablesUpdate<'leave_requests'>;
export type TimeEntryInsert          = TablesInsert<'time_entries'>;
export type ReportAuditLogInsert     = TablesInsert<'report_audit_log'>;

// ── Composite / joined types (not generated by supabase gen types) ───────────

export type OrderWithItems = OrderRow & {
  order_items: OrderItemRow[];
  branch: BranchRow | null;
};

export type ShiftWithStaff = ShiftRow & {
  staff_basic: Pick<StaffBasicRow, 'name' | 'role'>;
};

export type KDSQueueItem = KDSQueueRow & {
  order_items: Pick<OrderItemRow, 'name_ar' | 'name_en' | 'quantity' | 'selected_size' | 'selected_variant'>;
  orders: Pick<OrderRow, 'customer_name' | 'notes' | 'branch_id' | 'status' | 'created_at'>;
};

export type KDSOrder = Omit<OrderRow, 'status'> & {
  status: 'accepted' | 'preparing' | 'ready';
  order_items: Array<{
    id: string;
    name_ar: string;
    name_en: string;
    quantity: number;
    selected_size: string | null;
    selected_variant: string | null;
  }>;
};

export type DriverOrder = OrderRow & {
  order_items: Pick<OrderItemRow, 'name_ar' | 'name_en' | 'quantity' | 'selected_size' | 'selected_variant'>[];
  payments?: { method: PaymentMethod } | null;
  cash_settlement?: Array<{ handover_id: string }> | null;
  // Added by migration 037 — manually typed until types.ts is regenerated
  cash_settled_at?: string | null;
  cash_settlement_id?: string | null;
  // Added by migration 040
  tip_bhd?: number | null;
};

// Re-narrow `audit_logs.action` for safer call sites — the column is a generic
// `string` in Postgres but only ever holds one of three values in practice.
export type TypedAuditLogRow = Omit<AuditLogRow, 'action'> & { action: AuditLogAction };
