// Single source of truth for menu category ids.
// IDs are generated by `slugify(category.en)` in src/lib/menu.ts and must stay
// in sync with src/data/menu.json. Adding a new category here is a deliberate
// product decision — do not invent ids ad-hoc.

export const MENU_CATEGORIES = [
  { id: 'kahramana-signature-selection', ar: 'مختارات كهرمانة للتوقيع',     en: 'Kahramana Signature Selection' },
  { id: 'baghdadi-culinary-masterpieces', ar: 'روائع المائدة البغدادية',     en: 'Baghdadi Culinary Masterpieces' },
  { id: 'the-cold-mezza-garden',          ar: 'بستان المقبلات الباردة',      en: 'The Cold Mezza Garden' },
  { id: 'the-hot-mezza-garden',           ar: 'بستان المقبلات الساخنة',      en: 'The Hot Mezza Garden' },
  { id: 'garden-fresh-salads',            ar: 'سلطات نضارة البساتين',        en: 'Garden Fresh Salads' },
  { id: 'warm-and-comforting-soups',      ar: 'شوربات دافئة',                en: 'Warm & Comforting Soups' },
  { id: 'the-authentic-stew-house',       ar: 'بيت المرق الأصيل',            en: 'The Authentic Stew House' },
  { id: 'the-fatteh-collection',          ar: 'مجموعة الفتات الفاخرة',       en: 'The Fatteh Collection' },
  { id: 'baghdadi-tandoor-selection',     ar: 'مختارات التنور البغدادية',    en: 'Baghdadi Tandoor Selection' },
  { id: 'the-shawarma-suite-kaas',        ar: 'أجنحة الشاورما العراقية (الكص)', en: 'The Shawarma Suite (Kaas)' },
  { id: 'artisan-stone-oven-pizza',       ar: 'بيتزا الفرن الحجري',          en: 'Artisan Stone-Oven Pizza' },
  { id: 'traditional-sandwiches',         ar: 'سندويشات بغدادية',            en: 'Traditional Sandwiches' },
  { id: 'the-heritage-breakfast',         ar: 'الفطور البغدادي التراثي',     en: 'The Heritage Breakfast' },
  { id: 'the-sweet-finale',               ar: 'ختامها مسك (الحلويات)',       en: 'The Sweet Finale' },
  { id: 'fresh-signature-juices',         ar: 'عصائر كهرمانة الطبيعية',      en: 'Fresh Signature Juices' },
  { id: 'the-heritage-tea-and-coffee',    ar: 'ركن الشاي والقهوة العريق',    en: 'The Heritage Tea & Coffee' },
] as const

export type MenuCategoryId = typeof MENU_CATEGORIES[number]['id']

export const MENU_CATEGORY_IDS: readonly string[] = MENU_CATEGORIES.map((c) => c.id)

export function isValidMenuCategoryId(id: string): id is MenuCategoryId {
  return MENU_CATEGORY_IDS.includes(id)
}

export function getMenuCategory(id: string) {
  return MENU_CATEGORIES.find((c) => c.id === id)
}
