import ExcelJS from 'exceljs'

export interface ExcelSheetConfig {
  sheetName: string
  headers:   string[]
  rows:      (string | number)[][]
}

export async function buildExcelBlob(
  reportName: string,
  generatedAt: string,
  filterLabel: string,
  sheets: ExcelSheetConfig[],
): Promise<Blob> {
  const wb = new ExcelJS.Workbook()
  wb.creator = 'Kahramana Baghdad'
  wb.created = new Date()

  // Summary sheet
  const summaryWS = wb.addWorksheet('Summary')
  summaryWS.columns = [{ width: 24 }, { width: 40 }]
  const summaryRows: (string | number)[][] = [
    ['Kahramana Baghdad — Reports'],
    [],
    ['Report Name:', reportName],
    ['Generated:',  generatedAt],
    ['Filters:',    filterLabel],
    [],
    ...sheets.map((s) => [`${s.sheetName} rows:`, s.rows.length]),
    [],
    ['Generated by Kahramana Baghdad Enterprise Reports'],
  ]
  for (const row of summaryRows) {
    summaryWS.addRow(row)
  }

  // Data sheets
  for (const sheet of sheets) {
    const ws = wb.addWorksheet(sheet.sheetName.slice(0, 31))

    ws.columns = sheet.headers.map((h, i) => ({
      width: Math.max(
        h.length + 2,
        ...sheet.rows.map((r) => String(r[i] ?? '').length + 1),
        8,
      ),
    }))

    const headerRow = ws.addRow(sheet.headers)
    headerRow.font = { bold: true }

    for (const row of sheet.rows) {
      ws.addRow(row)
    }

    ws.views = [{ state: 'frozen', xSplit: 0, ySplit: 1, activeCell: 'A2' }]
  }

  const buf = await wb.xlsx.writeBuffer()
  return new Blob([buf], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  })
}
