import * as XLSX from 'xlsx'

export interface ExcelSheetConfig {
  sheetName: string
  headers:   string[]
  rows:      (string | number)[][]
}

export function buildExcelBlob(
  reportName: string,
  generatedAt: string,
  filterLabel: string,
  sheets: ExcelSheetConfig[],
): Blob {
  const wb = XLSX.utils.book_new()

  // Summary sheet
  const summaryAoA: (string | number)[][] = [
    ['Kahramana Baghdad — Reports'],
    [],
    ['Report Name:', reportName],
    ['Generated:',  generatedAt],
    ['Filters:',    filterLabel],
    [],
    ...sheets.map((s) => [`${s.sheetName} rows:`, s.rows.length]),
    [],
    ['Generated by Kahramana Baghdad Enterprise Reports'],
  ]
  const summaryWS = XLSX.utils.aoa_to_sheet(summaryAoA)
  summaryWS['!cols'] = [{ wch: 24 }, { wch: 40 }]
  XLSX.utils.book_append_sheet(wb, summaryWS, 'Summary')

  // Data sheets
  for (const sheet of sheets) {
    const aoa: (string | number)[][] = [sheet.headers, ...sheet.rows]
    const ws = XLSX.utils.aoa_to_sheet(aoa)

    // Auto-size columns
    ws['!cols'] = sheet.headers.map((h, i) => ({
      wch: Math.max(
        h.length + 2,
        ...sheet.rows.map((r) => String(r[i] ?? '').length + 1),
        8,
      ),
    }))

    // Freeze header row
    ws['!freeze'] = { xSplit: 0, ySplit: 1, topLeftCell: 'A2', activePane: 'bottomLeft' }

    XLSX.utils.book_append_sheet(wb, ws, sheet.sheetName.slice(0, 31))
  }

  const buf = XLSX.write(wb, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer
  return new Blob([buf], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  })
}
