-- ============================================================
-- Seed migration: run if menu_items_sync is empty
-- Safe to re-run (upsert on slug)
-- Generated from src/data/menu.json session 71
-- ============================================================

INSERT INTO menu_items_sync
  (slug, name_ar, name_en, price_bhd, station, last_synced_at, sync_source)
VALUES
  ('grills-kahramana-mix', 'مشاوي كهرمانة (6 أسياخ)', 'Kahramana Mixed Grill (6 skewers)', 4, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-ribs', 'ﺿﻠﻮع غنم فاخرة', 'Premium Lamb Ribs', 2.6, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-meat-kabab', 'كباب لحم عراقي', 'Iraqi Meat Kabab', 1.5, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-tikka-meat', 'تكة لحم', 'Meat Tikka', 3.2, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-grilled-neck', 'رقبة مشوية فاخرة', 'Premium Grilled Neck', 4, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-chicken-kabab', 'كباب دجاج', 'Chicken Kabab', 1.2, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-chicken-tikka', 'تكة دجاج', 'Chicken Tikka', 1.2, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-liver', 'معلاق مشوي (كبدة)', 'Grilled Liver', 2.6, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-chicken-wings', 'جوانح دجاج مشوية', 'Grilled Chicken Wings', 2.5, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-arayes', 'عرايس كهرمانة', 'Kahramana Arayes', 1.4, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-mix-grill', 'مشاوي مشكلة', 'Mix Grill Platter', 2.5, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-meat-grills', 'مشاوي لحم (أطباق)', 'Meat Grill Plates', 2.8, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-chicken-grills', 'مشاوي دجاج (أطباق)', 'Chicken Grill Plates', 2.1, 'grill'::kds_station, NOW(), 'menu.json'),
  ('grills-grilled-chicken', 'دجاج مشوي على الفحم', 'Charcoal Grilled Chicken', 1.6, 'grill'::kds_station, NOW(), 'menu.json'),
  ('mains-masgouf', 'المسكوف العراقي الأصيل (على حطب المشمش)', 'Authentic Iraqi Masgouf (Apricot Wood Fire)', 9, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-quzi-iraqi-lamb', 'قوزي لحم عراقي (ملكي)', 'Royal Iraqi Lamb Quzi', 4, 'main'::kds_station, NOW(), 'menu.json'),
  ('main-kharof', 'خروف كامل (للولائم)', 'Whole Lamb (Feasts)', 40, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-dlemiya', 'الدليمية البغدادية الأصيلة', 'Authentic Baghdadi Dlemiya', 3.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-dolma', 'الدولمة البغدادية (درة التاج)', 'The Crown Dolma (Baghdadi Style)', 3, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-lamb-neck-rice', 'رقبة اللحم المطهوة ببطء مع الأرز', 'Slow-Cooked Lamb Neck with Rice', 4, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-quzi-iraqi-chicken', 'قوزي دجاج عراقي', 'Iraqi Chicken Quzi', 2.4, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-meat-thareed', 'ثريد اللحم الأصيل', 'Authentic Meat Thareed', 3.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-biryani-meat', 'برياني اللحم الملكي', 'Royal Meat Biryani', 3.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-machbous-lamb', 'مجبوس اللحم الخليجي', 'Gulf Lamb Machboos', 3.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-bahraini-quzi-lamb', 'قوزي لحم بحريني', 'Bahraini Lamb Quzi', 3.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-meat-mandi', 'مندي اللحم اليمني', 'Yemeni Meat Mandi', 3.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-iraqi-shawarma-rice', 'شاورما عراقية مع الأرز', 'Iraqi Shawarma with Rice', 2.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-kabab-rice', 'كباب مع الأرز', 'Kabab with Rice', 2.2, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-stuffed-onion', 'بصل محشي', 'Stuffed Onions', 2.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-stuffed-zucchini', 'كوسا محشي', 'Stuffed Zucchini', 2.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('main-safi-fish-rice', 'سمك صافي مع الأرز', 'Safi Fish with Rice', 2.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-biryani-chicken', 'برياني الدجاج', 'Chicken Biryani', 1.9, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-machbous-chicken', 'مجبوس الدجاج', 'Chicken Machboos', 1.9, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-chicken-mandi', 'مندي الدجاج', 'Chicken Mandi', 1.9, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-bahraini-quzi-chicken', 'قوزي دجاج بحريني', 'Bahraini Chicken Quzi', 1.9, 'main'::kds_station, NOW(), 'menu.json'),
  ('main-rotisserie-chicken', 'دجاج شواية فاخر', 'Premium Rotisserie Chicken', 1.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-grilled-chicken-rice', 'دجاج مشوي مع الأرز', 'Grilled Chicken with Rice', 1.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-iraqi-shawarma-thareed', 'ثريد الشاورما العراقي', 'Iraqi Shawarma Thareed', 2.2, 'main'::kds_station, NOW(), 'menu.json'),
  ('mains-rice', 'الأرز العراقي والخليجي', 'Iraqi & Gulf Rice Selection', 0.8, 'main'::kds_station, NOW(), 'menu.json'),
  ('cold-apps-mix-appetizer', 'تشكيلة مقبلات كهرمانة الفاخرة', 'Kahramana Deluxe Mixed Appetizers', 3, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('cold-apps-mtabal', 'متبل باذنجان مشوي', 'Moutabal', 1.2, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('cold-apps-hummus', 'حمص بالطحينة الفاخرة', 'Premium Hummus', 1.2, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('cold-apps-hummus-meat', 'حمص باللحم المتبل', 'Hummus with Spiced Meat', 1.8, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('cold-apps-hummus-shawarma', 'حمص بشاورما عراقية', 'Hummus with Iraqi Shawarma', 1.8, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('cold-apps-pepper-hummus', 'حمص بالفلفل المشوي', 'Roasted Pepper Hummus', 1.2, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('cold-apps-vine-leaves', 'ورق عنب بالزيت', 'Vine Leaves with Olive Oil', 1.5, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('cold-apps-turshi', 'طرشي عراقي أصيل', 'Authentic Iraqi Pickles (Turshi)', 1, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('hot-apps-dolma', 'دولمة بغدادية (مقبلات)', 'Baghdadi Dolma (Appetizer)', 3, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('hot-apps-mosul-kubba', 'الكبة الموصلية الفاخرة', 'Premium Mosul Kubba', 2.5, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('hot-apps-halab-kubba', 'كبة حلب (كبة الأرز الشهيرة)', 'Famous Aleppo Rice Kubba', 2, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('hot-apps-burek-cheese', 'بورك الجبن المقرمش', 'Crispy Cheese Burek', 1.7, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('hot-apps-oroug', 'عروق عراقية', 'Authentic Iraqi Oroug', 1.2, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('hot-apps-hareesa', 'هريسة عراقية باللحم', 'Iraqi Lamb Hareesa', 1.6, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('hot-apps-madhroobah', 'مضروبة بحرينية أصيلة', 'Authentic Bahraini Madhroobah', 1.4, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('hot-apps-french-fries', 'بطاطس مقلية مقرمشة', 'Crispy French Fries', 1.4, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('salad-tabbouleh', 'تبولة خضراء منعشة', 'Fresh Green Tabbouleh', 1.5, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('salad-fattoush', 'فتوش بصلصة الرمان', 'Fattoush with Pomegranate Sauce', 1.5, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('salad-eggplant', 'سلطة باذنجان مشوي', 'Grilled Eggplant Salad', 1.2, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('salad-rocca', 'سلطة جرجير ودبس الرمان', 'Rocca & Pomegranate Salad', 1.5, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('salad-jajeek', 'جاجيك عراقي (خيار باللبن)', 'Iraqi Jajeek (Cucumber Yogurt)', 1.2, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('salad-green', 'سلطة خضراء موسمية', 'Seasonal Green Salad', 1, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('soup-sour-kubba', 'شوربة كبة حامض بغدادية', 'Baghdadi Sour Kubba Soup', 1.8, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('soup-lentil', 'شوربة عدس ذهبية', 'Golden Lentil Soup', 1.2, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('soup-mushroom', 'شوربة الفطر الكريمية', 'Creamy Mushroom Soup', 1.3, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('soup-red', 'الشوربة الحمراء (رمضانية)', 'Iraqi Red Soup', 0.8, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('stews-bamih', 'مرق البامية العراقي', 'Iraqi Okra Stew', 1, 'main'::kds_station, NOW(), 'menu.json'),
  ('stews-white-beans', 'مرق الفاصولياء البيضاء', 'White Bean Stew', 1, 'main'::kds_station, NOW(), 'menu.json'),
  ('stews-tabsi', 'تبسي الباذنجان', 'Eggplant Tabsi Stew', 1, 'main'::kds_station, NOW(), 'menu.json'),
  ('breakfast-fattat-vine-leaves', 'فتة ورق عنب ملكية', 'Royal Vine Leaves Fatteh', 3, 'main'::kds_station, NOW(), 'menu.json'),
  ('breakfast-fattat-eggplant-chickpeas', 'فتة باذنجان وحمص', 'Eggplant & Chickpea Fatteh', 3, 'main'::kds_station, NOW(), 'menu.json'),
  ('breakfast-fattat-falafel', 'فتة فلافل مميزة', 'Special Falafel Fatteh', 3, 'main'::kds_station, NOW(), 'menu.json'),
  ('pastry-lahm-bi-ajeen', 'لحم بعجين بغدادي الأصيل', 'Authentic Baghdadi Meat Bread', 1.8, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-meat-pie', 'فطيرة لحم عراقية', 'Iraqi Meat Pie', 1.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-meat-shawarma-cheese', 'فطيرة شاورما لحم وجبن', 'Meat Shawarma & Cheese Pie', 1.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-meat-kabab-cheese', 'فطيرة كباب لحم وجبن', 'Meat Kabab & Cheese Pie', 1.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-akkawi', 'فطيرة عكاوي ملكية', 'Royal Akkawi Cheese Pie', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-zaatar-plain', 'فطيرة زعتر عطري', 'Aromatic Zaatar Pie', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-iraqi-bread-dozen', 'صمون عراقي طازج (درزن)', 'Fresh Iraqi Bread (Dozen)', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-fatayer-dozen', 'فطائر مشكلة (درزن)', 'Assorted Pastries (Dozen)', 2.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-labnah', 'فطيرة لبنة كريمية', 'Creamy Labnah Pie', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-labnah-cheese', 'فطيرة لبنة مع جبن', 'Labnah & Cheese Pie', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-spinach-labnah', 'فطيرة سبانخ طازجة', 'Fresh Spinach Pie', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-honey-labnah', 'فطيرة لبنة وعسل', 'Honey & Labnah Pie', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-zaatar-labnah', 'فطيرة زعتر ولبنة', 'Zaatar & Labnah Pie', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-sausage-labnah', 'فطيرة سجق ولبنة', 'Sausage & Labnah Pie', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-sausage-cheese-labnah', 'فطيرة سجق ولبنة وجبن', 'Cheese & Sausage & Labnah', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-meat-shawarma-labnah', 'فطيرة شاورما لحم ولبنة', 'Iraqi Meat Shawarma & Labnah Pie', 1.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-chicken-shawarma-labnah', 'فطيرة شاورما دجاج ولبنة', 'Chicken Shawarma & Labnah Pie', 1.3, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-falafel-labnah', 'فطيرة فلافل ولبنة', 'Falafel & Labnah Pie', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-spring-pie', 'فطيرة ربيع كهرمانة', 'Kahramana Spring Pie', 1.4, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-cheese', 'فطيرة جبن كلاسيكية', 'Classic Cheese Pie', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-zaatar-cheese', 'فطيرة زعتر وجبن', 'Zaatar & Cheese Pie', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-sausage-cheese', 'فطيرة سجق جبن', 'Sausage & Cheese Pie', 1.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-chicken-shawarma-cheese', 'فطيرة شاورما دجاج وجبن', 'Chicken Shawarma & Cheese Pie', 1.4, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-meat-spinach', 'فطيرة لحم وسبانخ', 'Meat & Spinach Pie', 1.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pastry-chicken-spinach', 'فطيرة دجاج وسبانخ', 'Chicken & Spinach Pie', 1.4, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('shawarma-iraqi-meat-plate', 'صحن كص لحم عراقي فاخر', 'Premium Iraqi Meat Shawarma Plate', 2.5, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-iraqi-meat', 'شاورما لحم عراقية (خبز تنور)', 'Iraqi Meat Shawarma (Tandoor)', 1.1, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-iraqi-chicken', 'شاورما دجاج عراقية (خبز تنور)', 'Iraqi Chicken Shawarma (Tandoor)', 1, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-arabic-mix', 'صحن عربي مشكل (لحم ودجاج)', 'Arabi Mix Shawarma Plate', 1.8, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-arabic-meat', 'عربي لحم', 'Arabi Meat Shawarma', 1.8, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-arabic-chicken', 'عربي دجاج', 'Arabi Chicken Shawarma', 1.7, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-samoon-meat', 'صمون عراقي لحم (كص)', 'Meat Shawarma in Samoon', 1.1, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-lebnani-meat', 'شاورما لحم (خبز لبناني)', 'Meat Shawarma (Lebanese Bread)', 0.6, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-lebnani-chicken', 'شاورما دجاج (خبز لبناني)', 'Chicken Shawarma (Lebanese Bread)', 0.5, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-saj-meat', 'صاج لحم (ملغوم)', 'Meat Saj (Malghoom)', 0.6, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-chapati-meat', 'شباتي لحم', 'Meat Chapati Shawarma', 0.7, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('shawarma-chapati-chicken', 'شباتي دجاج', 'Chicken Chapati Shawarma', 0.6, 'shawarma'::kds_station, NOW(), 'menu.json'),
  ('pizza-kahramana-signature', 'بيتزا كهرمانة (التوقيع الخاص)', 'Kahramana Signature Pizza', 2.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pizza-shawarma', 'بيتزا شاورما عراقية', 'Iraqi Shawarma Pizza', 2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pizza-kabab', 'بيتزا كباب عراقي', 'Iraqi Kabab Pizza', 2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pizza-pepperonata', 'بيتزا بابروني كلاسيك', 'Classic Pepperoni Pizza', 2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pizza-margarita', 'بيتزا مارغريتا', 'Margherita Pizza', 1.6, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pizza-vegetarian', 'بيتزا الخضار', 'Vegetarian Pizza', 1.8, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pizza-pollo', 'بيتزا بولو (دجاج ومشروم)', 'Pollo Pizza (Chicken & Mushroom)', 1.9, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pizza-spinach', 'بيتزا السبانخ', 'Spinach Pizza', 1.8, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('pizza-jalapeno-chicken', 'بيتزا دجاج جلابينو حار', 'Spicy Jalapeno Chicken Pizza', 2.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-meat-kabab', 'سندويش كباب لحم عراقي', 'Meat Kabab Sandwich', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-meat-tikka', 'سندويش تكة لحم', 'Meat Tikka Sandwich', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-chicken-kabab', 'سندويش كباب دجاج', 'Chicken Kabab Sandwich', 0.9, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-chicken-tikka', 'سندويش تكة دجاج', 'Chicken Tikka Sandwich', 0.9, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-grilled-liver', 'سندويش معلاق مشوي (كبدة)', 'Grilled Liver Sandwich', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-kubba', 'سندويش كبة مقلية', 'Fried Kubba Sandwich', 0.9, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-falafel', 'سندويش فلافل مقرمشة', 'Crispy Falafel Sandwich', 0.8, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-beef-liver', 'سندويش كبد عجل', 'Beef Liver Sandwich', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-chicken-liver', 'سندويش كبد دجاج', 'Chicken Liver Sandwich', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-makhlama', 'سندويش مخلمة عراقية', 'Iraqi Makhlama Sandwich', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-shakshouka', 'سندويش شكشوكة', 'Shakshouka Sandwich', 0.9, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-special-shakshouka', 'سندويش شكشوكة خاصة (بالجبن)', 'Special Cheese Shakshouka Sandwich', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('sandwiches-tomato-special', 'سندويش طاوة طماطم مكرملة', 'Caramelized Tomato Tawa Sandwich', 0.8, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-plates-bagella-bil-dihen', 'باقلاء بالدهن (بغدادية الأصيلة)', 'Authentic Fava Beans bil Dihen', 2.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-tawat-makhlama', 'مخلمة عراقية كلاسيكية', 'Classic Iraqi Makhlama', 2.1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-eggs-fried-eggs', 'بيض عيون بالدهن الحر', 'Fried Eggs in Pure Ghee', 1.6, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-eggs-shakshouka-special', 'شكشوكة كهرمانة الخاصة', 'Kahramana Special Shakshouka', 2.2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-eggs-meat', 'بيض مع اللحم المتبل', 'Eggs with Seasoned Meat', 2.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-eggs-basterma', 'بيض مع البسترما', 'Eggs with Basterma', 2.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-tawat-tomato-tawah', 'طاوة طماطم مكرملة', 'Tomato Tawah Special', 1.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-tawat-chicken-liver', 'كبد دجاج بدبس الرمان', 'Chicken Liver with Pomegranate', 2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-tawat-beef-liver', 'كبد عجل مشوي', 'Grilled Beef Liver', 2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-plates-halloumi', 'حلومي مشوي', 'Grilled Halloumi', 2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-plates-falafel', 'صحن فلافل مقرمشة', 'Crispy Falafel Plate', 1.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-plates-dibis-rashi', 'دبس وراشي (المذاق التراثي)', 'Dibis w Rashi (Traditional)', 1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-plates-lablabeh', 'لبلبي عراقي دافئ', 'Warm Iraqi Lablabeh', 0.8, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-plates-msabaha', 'مسبحة بالطحينة', 'Msabaha with Tahini', 2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-plates-foul-mdammas', 'فول مدمس بالخلطة الخاصة', 'Foul Mdammas Special', 2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-plates-labneh', 'لبنة مصفاة فاخرة', 'Premium Strained Labneh', 1.5, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-plates-debis-dehin', 'دبس ودهن (حلو ومالح)', 'Debis w Dehin (Sweet & Savory)', 2, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-plates-bagella', 'باقلاء مسلوقة', 'Boiled Fava Beans', 0.8, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-eggs-tomatoes', 'بيض مع الطماطم', 'Eggs with Tomatoes', 1.9, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-eggs-shakshouka', 'شكشوكة كلاسيكية', 'Classic Shakshouka', 2.1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-eggs-potato', 'بيض مع البطاطس المقرمشة', 'Eggs with Crispy Potatoes', 1.7, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-eggs-cheese', 'بيض مع الجبن الذائب', 'Eggs with Melted Cheese', 2.1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('breakfast-eggs-zaatar', 'بيض مع الزعتر العطري', 'Eggs with Aromatic Zaatar', 2.1, 'bakery'::kds_station, NOW(), 'menu.json'),
  ('desserts-umm-ali', 'أم علي الملكية بالمكسرات', 'Royal Umm Ali with Nuts', 1.5, 'main'::kds_station, NOW(), 'menu.json'),
  ('desserts-fruit-salad', 'سلطة الفواكه الموسمية المنعشة', 'Refreshing Seasonal Fruit Salad', 2, 'main'::kds_station, NOW(), 'menu.json'),
  ('drinks-avocado', 'عصير أفوكادو ملكي', 'Royal Avocado Juice', 1.6, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-kahramana-cocktail', 'كوكتيل كهرمانة الخاص', 'Kahramana Special Cocktail', 1.4, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-strawberry', 'عصير فراولة طبيعي', 'Natural Strawberry Juice', 1.3, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-orange', 'عصير برتقال طازج', 'Fresh Orange Juice', 1.2, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-lemon-mint', 'عصير ليمون بالنعناع المنعش', 'Refreshing Lemon Mint Juice', 1.1, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-pomegranate', 'عصير رمان طبيعي', 'Natural Pomegranate Juice', 1.1, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-mango', 'عصير مانجو استوائي', 'Tropical Mango Juice', 1.1, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-laban-mint', 'لبن بالنعناع البارد', 'Chilled Laban with Mint', 1, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-soft-drinks', 'مشروبات غازية باردة', 'Chilled Soft Drinks', 0.4, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-water', 'مياه معدنية', 'Mineral Water', 0.2, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-iraqi-tea', 'شاي عراقي مهيّل (مخدر)', 'Iraqi Cardamom Tea (Mukhader)', 0.5, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-karak-tea', 'شاي كرك أصيل', 'Authentic Karak Tea', 0.6, 'appetizer_drinks'::kds_station, NOW(), 'menu.json'),
  ('drinks-black-lemon-tea', 'شاي حامض (نومي بصرة)', 'Iraqi Black Lemon Tea', 0.5, 'appetizer_drinks'::kds_station, NOW(), 'menu.json')
ON CONFLICT (slug) DO UPDATE SET
  name_ar        = EXCLUDED.name_ar,
  name_en        = EXCLUDED.name_en,
  price_bhd      = EXCLUDED.price_bhd,
  station        = EXCLUDED.station,
  last_synced_at = EXCLUDED.last_synced_at,
  sync_source    = EXCLUDED.sync_source;
